// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthOps struct {
	Login *LoginResponse `json:"login"`
}

type LoginInput struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Success bool    `json:"success"`
	Token   *string `json:"token,omitempty"`
}
